#!/usr/bin/env python

JUDGE_TIMEOUT = 14
JUDGE_EOF = 15
JUDGE_WRONG_MESSAGE = 11
JUDGE_SCORES_TIMEOUT = 16
JUDGE_SCORES_EOF = 17
JUDGE_WRONG_SCORES = 12
NOT_EXISTING_KILL = 18
NOT_EXISTING_MESSAGE = 13
JUDGE_WRITE = 104
